### ISSUE TITLE
Get boom deployment as kustomizable resource

### ISSUE THREAD

**Issue by buehler** [caos/orbos#145]
It would be nice to actually have the yaml definition for boom itself (the jumpstart) as a kustomize yaml. Then one could just create a simple kustomization yaml and reference the repository:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: caos-system

resources:
  - github.com/caos/boom/build/.......?ref=v1.4.2

# optional stuff
```
