### ISSUE TITLE
Allow plugin installation in grafana

### ISSUE THREAD

**Issue by buehler** [caos/orbos#148]
It would be nice if one could add a list of plugins that should be installed into grafana.

As I'm aware of, this was somehow possible with flags and env vars.

as an example:
```yaml
grafana:
  plugins:
    - grafana-piechart-panel
    - grafana-clock-panel
```
