### ISSUE TITLE
Structured secrets.yml

### ISSUE THREAD

**Issue by eliobischof** [caos/orbos#27]
```yaml
myorbmycluster_kubeconfig:
  encoding: Base64
  encryption: AES256
  value: xyz
myorbmyclustermyprovider_bootstrapkey:
  encoding: Base64
  encryption: AES256
  value: xyz
myorbmyclustermyprovider_maintenancekey:
  encoding: Base64
  encryption: AES256
  value: xyz
myorbmyclustermyprovider_maintenancekey_pub:
  encoding: Base64
  encryption: AES256
  value: xyz
```

becomes:
```yaml
kind: orbiter.caos.ch/Secrets
version: v0
spec:
  myorb:
    mycluster:
      kubeconfig:
        encoding: Base64
        encryption: AES256
        value: xyz
      myprovider:
        bootstrapkey:
          encoding: Base64
          encryption: AES256
          value: xyz
        maintenancekey:
          encoding: Base64
          encryption: AES256
          value: xyz
        maintenancekey_pub:
          encoding: Base64
          encryption: AES256
          value: xyz
```
