### ISSUE TITLE
K8s CoreDNS should not run on the same Master multiple times

### ISSUE THREAD

**Issue by fforootd** [caos/orbos#273]
## Problem

On a customer cluster we had both DNS scheduled to the same master which ended in a short outage after rebooting a master.

## Solution

- Change to a `daemonSet`
- Use `Anti-Affinity`

**Comment by fforootd** [comment]
relates to this 😁 https://github.com/kubernetes/kubeadm/issues/1416

**Comment by thesephirot** [comment]
as well as https://github.com/coredns/deployment/tree/master/kubernetes

in my opinion a "simple patch" for the affinity should solve the issue

**Comment by thesephirot** [comment]
@eliobischof the needed patch would be:

```
kubectl -n kube-system patch deployment coredns -p '{"spec":{"template":{"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"k8s-app","operator":"In","values":["kube-dns"]}]},"topologyKey":"kubernetes.io/hostname"}]}}}}}}'
```

**Comment by thesephirot** [comment]
Tested:

```
coredns-6955765f44-55l9p                   1/1     Terminating   7          171d   100.127.170.183   master01   <none>           <none>
coredns-6955765f44-k2jml                   1/1     Terminating   9          171d   100.127.170.184   master01   <none>           <none>
coredns-bbc5564c8-2jptl                    1/1     Running       0          9s     100.127.171.23    master03   <none>           <none>
coredns-bbc5564c8-czzwh                    0/1     Running       0          9s     100.127.170.254   master02   <none>           <none>
```

**Comment by eliobischof** [comment]
I suggest we use `preferredDuringSchedulingIgnoredDuringExecution` so that small clusters nodes keep being drainable and are HA at the pods level:

```yaml
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
```
