### ISSUE TITLE
Static to Dynamic RouterID for Keepalived config

### ISSUE THREAD

**Issue by tribock** [caos/orbos#619]
The RouterID is hardcoded. This leads to misbehaviour when multiple clusters are running in the same subnet.
Therefore the RouterID should be configurable through the orbiter.yml file.

e.g.:

```yaml
kind: orbiter.caos.ch/Orb
version: v0
clusters: []
providers:
  onprem:
    kind: orbiter.caos.ch/StaticProvider
    version: v1
    spec:
      externalinterfaces:
      - eth0 
    loadbalancing:
      kind: orbiter.caos.ch/DynamicLoadBalancer
      version: v2
      spec:
        workers:
        - ip: 10.2.2.1
          # new
          routerID: 55
        masters:
        - ip: 10.1.1.2
          # new
          routerID: 54
```
