### ISSUE TITLE
feat: BOOM: allow custom version for tools

### ISSUE THREAD

**Issue by buehler** [caos/orbos#621]
In response to https://github.com/caos/orbos/issues/620:

A (kind of) must have feature would be to enable people to use their own versions.
Boom (and / or caos) can provide defaults which guarantee to be compatible among each other, but allow the user to overwrite a version in `boom.yaml` if he wishes to do so.

If one person likes to keep the software as new as possible, this would enable them to do so. If own versions are used, there does not need to be any guarantee in place for compatibility.

For example, the custom versioning could support custom docker images and custom helm versions?
Or maybe just custom helm chat versions.

```yaml
apiVersion: boom.caos.ch/v1beta2
kind: Toolset
metadata:
  name: bumbum
spec:
  boom:
    version: v1.3.1
  reconciling:
    version: v1.8.4
```
